// Generated by tools/crab_art.py from tools/art/crab.json. Do not edit:
// change crab.json and run `python tools/crab_art.py`.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// The dancing crab's art: a 16-entry palette (index 0 transparent), the
// layer frames as 4-bit indices, and where the rig places each layer.
// Everything is const, in flash. The motion is lib/core/CrabPose.
#pragma once
#include <cstdint>

namespace crab {

// A layer frame: w x h native pixels, 2 per byte (high nibble = left pixel),
// each row padded to a whole byte.
struct Frame {
  uint8_t w, h;
  const uint8_t* px;
};

inline uint8_t pixel(const Frame& f, int x, int y) {
  const uint8_t b = f.px[y * ((f.w + 1) / 2) + x / 2];
  return (x & 1) ? (b & 0x0F) : (b >> 4);
}

enum FrameId : uint8_t {
  kBody,  // body, 24 x 15
  kBodySquash,  // body_squash, 26 x 13
  kBodyStretch,  // body_stretch, 22 x 16
  kEyes,  // eyes, 16 x 14
  kEyesHappy,  // eyes_happy, 16 x 14
  kEyesLook,  // eyes_look, 16 x 14
  kClawOpen,  // claw_open, 12 x 11
  kClawClosed,  // claw_closed, 12 x 11
  kArm,  // arm, 4 x 1
  kLegs,  // legs, 34 x 7
  kLegsSplay,  // legs_splay, 34 x 7
  kLegsAir,  // legs_air, 34 x 7
  kFxSnap,  // fx_snap, 11 x 5
  kFrameCount
};

constexpr int kPaletteSize = 16;
// Palette: 0 transparent, 1 outline, 2 shade, 3 red, 4 orange, 5 highlight, 6 white, 7 pupil, 8 blush, 9 mouth, 10 leg, 11 tongue, 12 gold, 13 shadow, 14 ground, 15 beat_dot.
constexpr uint8_t kShadowIx = 13;  // 's': drawn by the view, not in a frame
constexpr uint8_t kGroundIx = 14;  // 'g': drawn by the view, not in a frame
constexpr uint8_t kBeatDotIx = 15;  // 'a': drawn by the view, not in a frame
extern const uint8_t kPalette[kPaletteSize][3];      // RGB888, dancing
extern const uint8_t kPaletteIdle[kPaletteSize][3];  // RGB888, no beat (dimmed, half grey)
extern const Frame kFrames[kFrameCount];

// ---- rig: native px, relative to the crab's origin (x right from the box's
// centre, y up from kOriginY is negative). Box coordinates are screen px.
constexpr int kScale = 3;  // native px -> screen px, integer only
constexpr int kBoxW = 120, kBoxH = 150, kGroundY = 142;
constexpr int kOriginX = 60, kOriginY = 145;  // the ground line is rows kOriginY..kOriginY + 1
constexpr int kLegsX = -17, kLegsY = -7;
// Top-left of kBody, kBodySquash, kBodyStretch.
constexpr int8_t kBodyXY[3][2] = {{-12, -19}, {-13, -16}, {-11, -21}};
constexpr int kEyesDx = -8, kEyesAbove = 11;  // eye layer: x, rows above the body's top
constexpr int kClawX = 6, kClawW = 12, kClawH = 11, kClawBelowTop = 9;  // the right claw; the left one is mirrored
constexpr int kArmCol = 2, kArmW = 4, kArmEnd = 8;  // arm tile: x in the claw, width, last row below the body top
constexpr int kFxW = 11, kFxAbove = 6;  // snap spark: width, rows above the claw's top
constexpr int kShadowW = 66;  // screen px wide on the ground
constexpr float kShadowShrink = 2.0f;  // px narrower per px of hop
constexpr int kShadowY0 = 144, kShadowY1 = 147;  // rows [y0, y1), over the ground line

}  // namespace crab
