// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 IrosTheBeggar
// Generated by tools/make_logo.py from tools/art/mstream-logo.svg (mStream's
// logo, GPL-3.0). Do not edit: run `python tools/make_logo.py`.
//
// The mStream logo for the boot screen, 240 x 47 px: run-length coded rows of
// parts and coverage (lib/core/RleImage.h reads them; the code is described
// in the tool). The part's colours are the boot screen's (BootLayout.h).
#pragma once
#include <cstdint>

namespace logo {

constexpr int kW = 240, kH = 47;
constexpr int kParts = 3;  // 1 the word "stream", 2 the outer bars, 3 the middle bar
constexpr int kLevels = 32;  // a pixel's coverage, 1..kLevels
extern const uint8_t kData[];
constexpr uint32_t kSize = 2182;

// For the host test: each part's pixels, and their coverage summed.
constexpr uint32_t kPixels[kParts + 1] = {0, 3785, 906, 408};
constexpr uint32_t kCoverage[kParts + 1] = {0, 104881, 26533, 11968};

}  // namespace logo
