#!/usr/bin/env python3
"""Generates the dancing crab's art (lib/core/CrabArt.h, CrabArt.cpp) from
tools/art/crab.json.

    python tools/crab_art.py            # regenerate
    python tools/crab_art.py --check    # exit 1 if the checked-in files are stale

crab.json holds the palette (one character per 4-bit index, '.' = 0 =
transparent), the idle palette, the layer frames as text grids, and the rig's
geometry (where each layer sits relative to the crab's origin). The motion
itself (hop, side-step, claws, idle loop) is code: lib/core/CrabPose.cpp,
described in docs/MASCOT-POC.md.

The frames are packed two pixels per byte (high nibble = the left pixel, each
row padded to a whole byte) and emitted as const arrays in a .cpp, so they
live in flash (.rodata) once, not in every file that includes the header.
Standard library only.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "art" / "crab.json"
OUT_H = ROOT / "lib" / "core" / "CrabArt.h"
OUT_CPP = ROOT / "lib" / "core" / "CrabArt.cpp"

# The code in CrabPose.cpp refers to these by name: the order is the FrameId enum.
ORDER = ["body", "body_squash", "body_stretch", "eyes", "eyes_happy", "eyes_look",
         "claw_open", "claw_closed", "arm", "legs", "legs_splay", "legs_air", "fx_snap"]
BODIES = ["body", "body_squash", "body_stretch"]  # consecutive, in this order (kBodyXY)
# Palette slots the view fills itself (not in any frame), by their character.
SLOTS = {"s": "kShadowIx", "g": "kGroundIx", "a": "kBeatDotIx"}


def enum_name(n):
    return "k" + "".join(w.capitalize() for w in n.split("_"))


def rgb(s):
    s = s.lstrip("#")
    return int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)


def pack(rows, idx):
    w = len(rows[0])
    out = []
    for r in rows:
        ix = [idx[c] for c in r]
        if w % 2:
            ix.append(0)
        out += [(ix[i] << 4) | ix[i + 1] for i in range(0, len(ix), 2)]
    return out


def load():
    doc = json.loads(SRC.read_text(encoding="utf-8"))
    chars = doc["chars"]
    if len(chars) != 16 or chars[0] != "." or len(set(chars)) != 16:
        sys.exit("crab.json: 'chars' must be 16 distinct characters, '.' first")
    idx = {c: i for i, c in enumerate(chars)}
    frames = doc["frames"]
    if sorted(frames) != sorted(ORDER):
        sys.exit(f"crab.json: frames must be exactly {ORDER}, got {list(frames)}")
    for name in ORDER:
        rows = frames[name]
        w = len(rows[0])
        if not 0 < w < 256 or not 0 < len(rows) < 256 or any(len(r) != w for r in rows):
            sys.exit(f"crab.json: frame {name} is not a rectangle of 1-255 px")
        bad = {c for r in rows for c in r} - set(chars)
        if bad:
            sys.exit(f"crab.json: frame {name} uses characters not in the palette: {sorted(bad)}")
        used = {c for r in rows for c in r} & set(SLOTS)
        if used:
            sys.exit(f"crab.json: frame {name} uses the view's own slots {sorted(used)}")
    if len(doc["palette"]) != 16 or len(doc["palette_idle"]) != 16:
        sys.exit("crab.json: both palettes need 16 entries")
    return doc, chars, idx


def c_rgb_table(name, colours, comment):
    body = ",\n".join(f"    {{0x{r:02X}, 0x{g:02X}, 0x{b:02X}}}" for r, g, b in colours)
    return f"// {comment}\nconst uint8_t {name}[kPaletteSize][3] = {{\n{body},\n}};\n"


def generate():
    doc, chars, idx = load()
    rig, box = doc["rig"], doc["box"]
    pal = [rgb(p["rgb"]) for p in doc["palette"]]
    pal_idle = [rgb(c) for c in doc["palette_idle"]]
    head = ("// Generated by tools/crab_art.py from tools/art/crab.json. Do not edit:\n"
            "// change crab.json and run `python tools/crab_art.py`.\n"
            "// SPDX-License-Identifier: GPL-3.0-or-later\n")

    # ---- header
    h = [head.rstrip(), "//",
         "// The dancing crab's art: a 16-entry palette (index 0 transparent), the",
         "// layer frames as 4-bit indices, and where the rig places each layer.",
         "// Everything is const, in flash. The motion is lib/core/CrabPose.",
         "#pragma once",
         "#include <cstdint>",
         "",
         "namespace crab {",
         "",
         "// A layer frame: w x h native pixels, 2 per byte (high nibble = left pixel),",
         "// each row padded to a whole byte.",
         "struct Frame {",
         "  uint8_t w, h;",
         "  const uint8_t* px;",
         "};",
         "",
         "inline uint8_t pixel(const Frame& f, int x, int y) {",
         "  const uint8_t b = f.px[y * ((f.w + 1) / 2) + x / 2];",
         "  return (x & 1) ? (b & 0x0F) : (b >> 4);",
         "}",
         "",
         "enum FrameId : uint8_t {"]
    for n in ORDER:
        rows = doc["frames"][n]
        h.append(f"  {enum_name(n)},  // {n}, {len(rows[0])} x {len(rows)}")
    h += ["  kFrameCount", "};", "",
          "constexpr int kPaletteSize = 16;",
          "// Palette: " + ", ".join(f"{i} {p['name']}" for i, p in enumerate(doc["palette"])) + "."]
    for c, name in SLOTS.items():
        h.append(f"constexpr uint8_t {name} = {idx[c]};  // '{c}': drawn by the view, not in a frame")
    h += ["extern const uint8_t kPalette[kPaletteSize][3];      // RGB888, dancing",
          "extern const uint8_t kPaletteIdle[kPaletteSize][3];  // RGB888, no beat (dimmed, half grey)",
          "extern const Frame kFrames[kFrameCount];",
          "",
          "// ---- rig: native px, relative to the crab's origin (x right from the box's",
          "// centre, y up from kOriginY is negative). Box coordinates are screen px.",
          f"constexpr int kScale = {doc['scale']};  // native px -> screen px, integer only",
          f"constexpr int kBoxW = {box['w']}, kBoxH = {box['h']}, kGroundY = {box['groundY']};",
          f"constexpr int kOriginX = {box['origin'][0]}, kOriginY = {box['origin'][1]};"
          "  // the ground line is rows kOriginY..kOriginY + 1",
          f"constexpr int kLegsX = {rig['legs'][0]}, kLegsY = {rig['legs'][1]};",
          "// Top-left of " + ", ".join(enum_name(b) for b in BODIES) + ".",
          "constexpr int8_t kBodyXY[3][2] = {" +
          ", ".join(f"{{{rig['body'][b][0]}, {rig['body'][b][1]}}}" for b in BODIES) + "};",
          f"constexpr int kEyesDx = {rig['eyes_dx']}, kEyesAbove = {rig['eyes_above_body_top']};"
          "  // eye layer: x, rows above the body's top",
          f"constexpr int kClawX = {rig['claw_right_x']}, kClawW = {rig['claw_w']}, kClawH = {rig['claw_h']}, "
          f"kClawBelowTop = {rig['claw_top_below_body_top']};  // the right claw; the left one is mirrored",
          f"constexpr int kArmCol = {rig['arm_col_in_claw']}, kArmW = {rig['arm_w']}, "
          f"kArmEnd = {rig['arm_end_below_body_top']};  // arm tile: x in the claw, width, last row below the body top",
          f"constexpr int kFxW = {rig['fx_w']}, kFxAbove = {rig['fx_above_claw_top']};"
          "  // snap spark: width, rows above the claw's top",
          f"constexpr int kShadowW = {rig['shadow']['w']};  // screen px wide on the ground",
          f"constexpr float kShadowShrink = {float(rig['shadow']['shrink_per_px'])}f;  // px narrower per px of hop",
          f"constexpr int kShadowY0 = {rig['shadow']['rows'][0]}, kShadowY1 = {rig['shadow']['rows'][1]};"
          "  // rows [y0, y1), over the ground line",
          "",
          "}  // namespace crab",
          ""]
    if rig["claw_left_x"] != -rig["claw_right_x"] - rig["claw_w"] or not rig["claw_left_flipped"]:
        sys.exit("crab.json: the left claw must mirror the right one")
    if [len(doc["frames"]["arm"][0]), len(doc["frames"]["arm"])] != [rig["arm_w"], 1]:
        sys.exit("crab.json: the arm tile must be arm_w x 1")
    if len(doc["frames"]["fx_snap"][0]) != rig["fx_w"]:
        sys.exit("crab.json: fx_w must be fx_snap's width")
    for n in ("claw_open", "claw_closed"):
        rows = doc["frames"][n]
        if [len(rows[0]), len(rows)] != [rig["claw_w"], rig["claw_h"]]:
            sys.exit(f"crab.json: {n} must be claw_w x claw_h")

    # ---- data
    total = 0
    c = [head, '#include "CrabArt.h"', "", "namespace crab {", "",
         c_rgb_table("kPalette", pal, "Dancing: " + ", ".join(p["rgb"] for p in doc["palette"])),
         c_rgb_table("kPaletteIdle", pal_idle, "No beat: the same indices, dimmed and half grey"),
         "namespace {"]
    for n in ORDER:
        rows = doc["frames"][n]
        data = pack(rows, idx)
        total += len(data)
        c.append(f"// {n}: {len(rows[0])} x {len(rows)}")
        c += [f"//   {r}" for r in rows]
        c.append(f"const uint8_t {enum_name(n)}Px[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            c.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
        c.append("};")
    c += ["}  // namespace", "", f"// {total} bytes of pixels",
          "const Frame kFrames[kFrameCount] = {"]
    for n in ORDER:
        rows = doc["frames"][n]
        c.append(f"    {{{len(rows[0])}, {len(rows)}, {enum_name(n)}Px}},")
    c += ["};", "", "}  // namespace crab", ""]
    return "\n".join(h), "\n".join(c)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the generated files are out of date")
    args = ap.parse_args()
    h, c = generate()
    if args.check:
        stale = [p for p, text in ((OUT_H, h), (OUT_CPP, c))
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)} (run python tools/crab_art.py)")
        sys.exit(1 if stale else 0)
    for p, text in ((OUT_H, h), (OUT_CPP, c)):
        p.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
