// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 IrosTheBeggar
//
// Writes lib/core/NameKeyTables.cpp: the Unicode tables behind
// lib/core/NameKey (docs/METADATA.md 5.4, "nameKey ... pinned for the
// contract"), taken from Rust's own std so the player's nameKey is the one
// the transfer software (Rust) computes:
//   - White_Space: char::is_whitespace;
//   - the default full lowercase mapping: char::to_lowercase (ranges of
//     single code points, plus the few that map to several);
//   - Final_Sigma's context classes (Cased, Case_Ignorable), which Rust's
//     str::to_lowercase uses for U+03A3 but doesn't export: probed through
//     str::to_lowercase itself. A capital sigma after "A" then c is final
//     when c is case-ignorable or cased; right after c alone, only when c is
//     cased and not case-ignorable. So c is "ignorable" (skipped in the
//     context) when the first holds and not the second, and "cased" when
//     the second holds.
//
// Run from the repository root (any rustc; the file records the Unicode
// version of the one used):
//   rustc -O tools/unicode_case.rs -o <tmp>/unicode_case
//   <tmp>/unicode_case > lib/core/NameKeyTables.cpp

use std::fmt::Write;

fn chars() -> impl Iterator<Item = (u32, char)> {
    (0u32..=0x10FFFF).filter_map(|c| char::from_u32(c).map(|ch| (c, ch)))
}

fn main() {
    let (ma, mi, up) = std::char::UNICODE_VERSION;
    let mut out = String::new();
    writeln!(out, "// SPDX-License-Identifier: GPL-3.0-or-later").unwrap();
    writeln!(out, "// Copyright (C) 2026 IrosTheBeggar").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "// GENERATED by tools/unicode_case.rs from Rust's std (Unicode {}.{}.{}); do not edit.", ma, mi, up).unwrap();
    writeln!(out, "// The tables behind NameKey.cpp: White_Space, the default full lowercase").unwrap();
    writeln!(out, "// mapping, and Final_Sigma's context classes (docs/METADATA.md 5.4).").unwrap();
    writeln!(out, "#include \"NameKey.h\"").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "namespace namekey {{").unwrap();
    writeln!(out, "namespace tables {{").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "const uint16_t kUnicodeVersion[3] = {{{}, {}, {}}};", ma, mi, up).unwrap();
    writeln!(out).unwrap();

    // White_Space, as ranges.
    let mut ws: Vec<(u32, u32)> = Vec::new();
    for (c, ch) in chars() {
        if ch.is_whitespace() {
            match ws.last_mut() {
                Some(r) if r.1 + 1 == c => r.1 = c,
                _ => ws.push((c, c)),
            }
        }
    }
    writeln!(out, "const Range kWhiteSpace[] = {{").unwrap();
    for (a, b) in &ws {
        writeln!(out, "    {{0x{:04X}, 0x{:04X}}},", a, b).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out, "const uint32_t kWhiteSpaceCount = sizeof(kWhiteSpace) / sizeof(kWhiteSpace[0]);").unwrap();
    writeln!(out).unwrap();

    // Lowercase: single code points as runs of one delta with a step of 1 or
    // 2 (the Latin Extended pairs alternate); several code points apart.
    let mut runs: Vec<(u32, u32, u32, i64)> = Vec::new(); // first, count, step, delta
    let mut special: Vec<(u32, Vec<u32>)> = Vec::new();
    for (c, ch) in chars() {
        let low: Vec<u32> = ch.to_lowercase().map(|x| x as u32).collect();
        if low.len() != 1 {
            special.push((c, low));
            continue;
        }
        if low[0] == c {
            continue;
        }
        let delta = low[0] as i64 - c as i64;
        let mut extended = false;
        if let Some(r) = runs.last_mut() {
            let last = r.0 + (r.1 - 1) * r.2;
            if r.3 == delta {
                if r.1 == 1 && (c - last == 1 || c - last == 2) {
                    r.2 = c - last;
                    r.1 += 1;
                    extended = true;
                } else if r.1 > 1 && c - last == r.2 {
                    r.1 += 1;
                    extended = true;
                }
            }
        }
        if !extended {
            runs.push((c, 1, 1, delta));
        }
    }
    writeln!(out, "const LowerRun kLower[] = {{").unwrap();
    for (first, count, step, delta) in &runs {
        writeln!(out, "    {{0x{:04X}, {}, {}, {}}},", first, count, step, delta).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out, "const uint32_t kLowerCount = sizeof(kLower) / sizeof(kLower[0]);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "const LowerSpecial kLowerSpecial[] = {{").unwrap();
    for (c, low) in &special {
        let mut v = [0u32; 3];
        for (i, x) in low.iter().enumerate().take(3) {
            v[i] = *x;
        }
        writeln!(out, "    {{0x{:04X}, {}, {{0x{:04X}, 0x{:04X}, 0x{:04X}}}}},", c, low.len(), v[0], v[1], v[2]).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out, "const uint32_t kLowerSpecialCount = sizeof(kLowerSpecial) / sizeof(kLowerSpecial[0]);").unwrap();
    writeln!(out).unwrap();

    // Final_Sigma's classes: 1 cased, 2 case-ignorable (skipped). The
    // digest covers every code point's lowercase (its code points as u32
    // little-endian), White_Space bit and class, as std gives them: the
    // player's test recomputes it from the compressed tables.
    let final_after = |s: String| s.to_lowercase().ends_with('\u{3C2}');
    let mut classes: Vec<(u32, u32, u8)> = Vec::new();
    let mut digest: u64 = 0xCBF29CE484222325;
    let mix = |b: u8, h: &mut u64| {
        *h ^= b as u64;
        *h = h.wrapping_mul(0x100000001B3);
    };
    for (c, ch) in chars() {
        let p1 = final_after(format!("A{}\u{3A3}", ch));
        let p2 = final_after(format!("{}\u{3A3}", ch));
        let class = if p1 && !p2 { 2u8 } else if p2 { 1u8 } else { 0u8 };
        for l in ch.to_lowercase() {
            for b in (l as u32).to_le_bytes() {
                mix(b, &mut digest);
            }
        }
        mix(if ch.is_whitespace() { 1 } else { 0 }, &mut digest);
        mix(class, &mut digest);
        if class == 0 {
            continue;
        }
        match classes.last_mut() {
            Some(r) if r.1 + 1 == c && r.2 == class => r.1 = c,
            _ => classes.push((c, c, class)),
        }
    }
    writeln!(out, "const ClassRange kSigmaContext[] = {{").unwrap();
    for (a, b, k) in &classes {
        writeln!(out, "    {{0x{:04X}, 0x{:04X} | {} << 24}},", a, b, k).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out, "const uint32_t kSigmaContextCount = sizeof(kSigmaContext) / sizeof(kSigmaContext[0]);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "const uint64_t kRustDigest = 0x{:016X}ull;", digest).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "}}  // namespace tables").unwrap();
    writeln!(out, "}}  // namespace namekey").unwrap();
    print!("{}", out);
}
